### ISSUE TITLE
Migrate to Kotlin

### ISSUE THREAD

**Issue by raghavtilak** [raghavtilak/AugmentedFaces#2] opened 2023-10-02 13:13 UTC

**Comment by poseidon2060** [comment] 2023-10-02 15:48
hey @raghavtilak can I work on this issue?
If yes please assign it to me

**Comment by raghavtilak** [comment] 2023-10-02 15:56
Hi @poseidon2060 ,
Yeah sure. Go for it 👍🏻

**Comment by poseidon2060** [comment] 2023-10-03 03:34
hey @raghavtilak 
![image](https://github.com/raghavtilak/AugmentedFaces/assets/101904141/a4533200-294c-49b6-8a4e-d548f380c365)
I am getting the following error while trying to run the app.
Can you help me with the error? I am unable to fix it

This is the complete error text
`Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make field private final java.lang.String java.io.File.path accessible: module java.base does not "opens java.io" to unnamed module @22310e4a
`

**Comment by raghavtilak** [comment] 2023-10-03 05:18
@poseidon2060 I have pushed the updated code. This should be resolved now. You can start working on your task.
This error mostly happens when the project is old. If you want to know more about this error, you can visit these links. 
[link1](https://stackoverflow.com/questions/67782975/how-to-fix-the-module-java-base-does-not-opens-java-io-to-unnamed-module) [link2](https://stackoverflow.com/questions/35842955/manifest-merger-failed-with-multiple-errors-in-android-studio)

**Comment by poseidon2060** [comment] 2023-10-03 08:45
> @poseidon2060 I have pushed the updated code. This should be resolved now. You can start working on your task.
> This error mostly happens when the project is old. If you want to know more about this error, you can visit these links. 
> [link1](https://stackoverflow.com/questions/67782975/how-to-fix-the-module-java-base-does-not-opens-java-io-to-unnamed-module) [link2](https://stackoverflow.com/questions/35842955/manifest-merger-failed-with-multiple-errors-in-android-studio)

Okay thankyou for your help😇

**Closed as completed** 2023-10-03 18:22 UTC
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest-accepted
